# Generated by Django 5.2.2 on 2025-11-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_portfolioprofile_about_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["-start_date"]},
        ),
    ]
