# Generated by Django 5.2.2 on 2025-11-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Blog Categories"},
        ),
    ]
